(()=>{"use strict";
const STORAGE_KEY="shian-live-player-score";
const POSITION_SEMITONES=[0,1,2,3,5,6,7,8,9,10,12,13,14,15,17,18,19,20,21,22,24];
const $=selector=>document.querySelector(selector),clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
let score=null,count=6,tempo=96,balance=50,muted=false,playing=false,pausedUnit=0,startContextTime=0,audioContext=null,masterGain=null,shamisenGain=null,vocalGain=null,scheduled=[],finishTimer=0;
function setStatus(message,error=false){const element=$("#status");element.textContent=message;element.classList.toggle("error",error)}
function parseMeter(value){const match=String(value||"2/4").match(/(\d+)\s*\/\s*(\d+)/);if(!match)return{capacity:8};const numerator=Number(match[1]),denominator=Number(match[2]);const capacity=16*numerator/denominator;return{capacity:Number.isFinite(capacity)&&capacity>0?capacity:8}}
function normalizeNote(note,isVocal=false){const m=Number(note?.m),s=Number(note?.s),p=Number(note?.p),d=Number(note?.d),v=String(note?.v||"");if(!Number.isInteger(m)||m<0||![1,2,3].includes(s)||!Number.isInteger(p)||p<0||![1,2,4].includes(d))return null;const kind=isVocal?String(note?.kind||"pitch"):"pitch";return{id:isVocal?String(note?.id||""):"",m,s,p,d,dotted:isVocal&&Boolean(note?.dotted),v,rest:isVocal?kind!=="pitch":Boolean(note?.rest),voice:isVocal?"vocal":"shamisen"}}
function normalizeRepeats(source,total){const byMeasure=new Map();(Array.isArray(source)?source:[]).forEach(part=>{const m=Number(part?.m),kind=part?.kind==="same2"||Number(part?.repeatCount)===2?"same2":part?.kind==="same1"||Number(part?.repeatCount)===1?"same1":null;if(!kind||!Number.isInteger(m)||m<1||m>=total)return;byMeasure.set(m,{m,repeatCount:kind==="same2"?2:1})});return byMeasure}
function normalizeMeasureLengths(source,total,capacity){const specials=source&&typeof source==="object"&&!Array.isArray(source)?source:{};return Array.from({length:total},(_,m)=>specials[String(m)]?.type==="hanma"&&Number(specials[String(m)].lengthRatio)===.5?capacity*.5:capacity)}
function buildPlaybackPlan(total,lengths,repeats){const segments=[],resolvedSource=[],starts=[];let cursor=0;for(let m=0;m<total;m++){starts[m]=cursor;const repeat=repeats.get(m),sourceM=repeat&&Number.isInteger(resolvedSource[m-1])?resolvedSource[m-1]:m,count=repeat&&sourceM!==m?repeat.repeatCount:1;resolvedSource[m]=sourceM;for(let copy=0;copy<count;copy++){const length=lengths[sourceM]||lengths[m]||1;segments.push({index:segments.length,sourceM,displayM:m,direct:sourceM===m&&copy===0,start:cursor,length});cursor+=length}}return{segments,endUnit:cursor}}
function expandPlaybackNotes(notes,plan,isVocal=false){const copiesById=new Map(),expanded=[];for(const segment of plan.segments){notes.filter(note=>note.m===segment.sourceM&&note.p<segment.length).forEach(note=>{const id=isVocal?`${note.id}@${segment.index}`:note.id,copy={...note,id,m:segment.index,timelineUnit:segment.start+note.p,sourceM:note.m,segmentIndex:segment.index,directSegment:segment.direct};expanded.push(copy);if(isVocal&&note.id){if(!copiesById.has(note.id))copiesById.set(note.id,[]);copiesById.get(note.id).push(copy)}})}return{notes:expanded,copiesById}}
function expandVocalSlurs(source,baseVocal,copiesById){const baseById=new Map(baseVocal.map(note=>[note.id,note])),result=[];(Array.isArray(source)?source:[]).forEach(slur=>{const startId=String(slur?.startId||""),endId=String(slur?.endId||""),startBase=baseById.get(startId),endBase=baseById.get(endId),starts=copiesById.get(startId)||[],ends=copiesById.get(endId)||[];if(!startBase||!endBase||startId===endId)return;if(startBase.m===endBase.m){starts.forEach(start=>{const end=ends.find(item=>item.segmentIndex===start.segmentIndex);if(end)result.push({startId:start.id,endId:end.id})})}else{const start=starts.find(item=>item.directSegment),end=ends.find(item=>item.directSegment&&item.timelineUnit>=Number(start?.timelineUnit));if(start&&end)result.push({startId:start.id,endId:end.id})}});return result}
function expandTuplets(source,baseNotes,plan){const columnDuration=(m,p)=>Math.max(0,...baseNotes.filter(note=>!note.rest&&note.m===m&&note.p===p).map(note=>note.d)),result=[];(Array.isArray(source)?source:[]).forEach(tuplet=>{const startM=Number(tuplet?.start?.m),startP=Number(tuplet?.start?.p),endM=Number(tuplet?.end?.m),endP=Number(tuplet?.end?.p),endDuration=columnDuration(endM,endP),targetUnits=Number(tuplet?.targetBeats)*4;if(tuplet?.type!=="triplet"||!Number.isInteger(startM)||!Number.isInteger(endM)||!Number.isInteger(startP)||!Number.isInteger(endP)||!endDuration||!Number.isFinite(targetUnits)||targetUnits<=0)return;const starts=plan.segments.filter(segment=>segment.sourceM===startM&&(startM===endM||segment.direct));starts.forEach(startSegment=>{const endSegment=startM===endM?startSegment:plan.segments.find(segment=>segment.sourceM===endM&&segment.direct&&segment.start>=startSegment.start);if(!endSegment)return;const start=startSegment.start+startP,writtenEnd=endSegment.start+endP+endDuration;if(writtenEnd>start)result.push({type:"triplet",start,writtenEnd,targetUnits})})});let lastEnd=-Infinity;return result.sort((a,b)=>a.start-b.start).filter(tuplet=>{if(tuplet.start<lastEnd)return false;lastEnd=tuplet.writtenEnd;return true})}
function validatePayload(payload){if(!payload||payload.format!=="shian-live-score"||!payload.score||!Array.isArray(payload.score.notes))throw new Error("演奏データの形式が正しくありません。");const source=payload.score,meter=String(source.meter||"2/4"),capacity=parseMeter(meter).capacity,baseNotes=source.notes.map(note=>normalizeNote(note)).filter(Boolean),baseVocal=(Array.isArray(source.vocalNotes)?source.vocalNotes:[]).map(note=>normalizeNote(note,true)).filter(Boolean),measureNumbers=[...baseNotes.map(note=>note.m),...baseVocal.map(note=>note.m),...(Array.isArray(source.scoreParts)?source.scoreParts:[]).map(part=>Number(part?.m)),...Object.keys(source.measureSpecials||{}).map(Number)].filter(Number.isInteger),highest=Math.max(-1,...measureNumbers),savedCount=Number(source.measureCount),total=Math.max(1,Number.isInteger(savedCount)&&savedCount>0?savedCount:0,highest+1),repeats=normalizeRepeats(source.scoreParts,total),lengths=normalizeMeasureLengths(source.measureSpecials,total,capacity),plan=buildPlaybackPlan(total,lengths,repeats),expandedNotes=expandPlaybackNotes(baseNotes,plan),expandedVocal=expandPlaybackNotes(baseVocal,plan,true),vocalSlurs=expandVocalSlurs(source.vocalSlurs,baseVocal,expandedVocal.copiesById),tuplets=expandTuplets(source.tuplets,baseNotes,plan);return{title:String(source.title||""),tuning:["本調子","二上り","三下り"].includes(source.tuning)?source.tuning:"二上り",meter,notes:expandedNotes.notes,tuplets,vocalNotes:expandedVocal.notes,vocalSlurs,playbackEndUnit:plan.endUnit}}
function receivePayload(payload){try{stop(true);score=validatePayload(payload);pausedUnit=0;const shamisenCount=score.notes.filter(note=>!note.rest).length,vocalCount=score.vocalNotes.filter(note=>!note.rest).length;setStatus(shamisenCount||vocalCount?`${score.tuning}・三味線 ${shamisenCount}音・唄 ${vocalCount}音`:"演奏できる音がありません。",!(shamisenCount||vocalCount))}catch(error){score=null;setStatus(error instanceof Error?error.message:"演奏データを読み込めませんでした。",true)}}
function loadInitial(){try{const raw=sessionStorage.getItem(STORAGE_KEY);if(raw)receivePayload(JSON.parse(raw))}catch(error){setStatus("演奏データを読み込めませんでした。",true);console.error(error)}}
function noteSemitone(value){if(value==="○"||value==="0")return 0;const number=Number(value);return Number.isInteger(number)&&number>=1&&number<=20?POSITION_SEMITONES[number]:null}
function tuningMode(value){return{"本調子":"hon","二上り":"niage","三下り":"sansage"}[value]||"niage"}
function frequencyFor(note){const semitone=noteSemitone(note.v),entry=window.ShianTuningMaster?.get(count,tuningMode(score?.tuning)),base=entry?.frequencies?.[note.s-1];return semitone===null||!Number.isFinite(base)?null:base*Math.pow(2,semitone/12)}
function buildTimeMap(){const tuplets=score?.tuplets||[];return raw=>{let shift=0;for(const tuplet of tuplets){const written=tuplet.writtenEnd-tuplet.start,scale=tuplet.targetUnits/written;if(raw<tuplet.start)break;if(raw<=tuplet.writtenEnd)return tuplet.start+shift+(raw-tuplet.start)*scale;shift+=tuplet.targetUnits-written}return raw+shift}}
function buildEvents(timeMap=buildTimeMap()){if(!score)return[];const groups=new Map();[...score.notes,...score.vocalNotes].forEach(note=>{const rawUnit=Number(note.timelineUnit),key=`${note.voice}:${rawUnit}`,writtenDuration=note.d*(note.voice==="vocal"&&note.dotted?1.5:1);if(!Number.isFinite(rawUnit))return;if(!groups.has(key))groups.set(key,{rawUnit,duration:writtenDuration,voice:note.voice,notes:[]});const event=groups.get(key);event.duration=Math.max(event.duration,writtenDuration);event.notes.push(note)});return[...groups.values()].map(event=>({...event,unit:timeMap(event.rawUnit),duration:timeMap(event.rawUnit+event.duration)-timeMap(event.rawUnit)})).sort((a,b)=>a.unit-b.unit)}
function buildVocalPlan(timeMap=buildTimeMap()){const ordered=(score?.vocalNotes||[]).map(note=>{const rawUnit=Number(note.timelineUnit);return{...note,unit:timeMap(rawUnit),d:timeMap(rawUnit+note.d*(note.dotted?1.5:1))-timeMap(rawUnit)}}).filter(note=>Number.isFinite(note.unit)).sort((a,b)=>a.unit-b.unit),byId=new Map(ordered.map(note=>[note.id,note])),consumed=new Set(),phrases=[];for(const slur of score?.vocalSlurs||[]){const start=byId.get(slur.startId),end=byId.get(slur.endId);if(!start||!end)continue;const low=Math.min(start.unit,end.unit),high=Math.max(start.unit,end.unit),inside=ordered.filter(note=>note.unit>=low&&note.unit<=high);let part=[];const flush=()=>{if(part.length>1){phrases.push(part);part.forEach(note=>consumed.add(note.id))}part=[]};inside.forEach(note=>{if(note.rest){flush();return}part.push(note)});flush()}return{phrases,singles:ordered.filter(note=>!note.rest&&!consumed.has(note.id))}}
async function ensureAudio(){if(!window.ShianAudioEngine||!window.ShianTuningMasterReady)throw new Error("三味線音源を読み込めませんでした。");await window.ShianTuningMasterReady;audioContext=await window.ShianAudioEngine.resume();await window.ShianAudioEngine.load();if(!masterGain){masterGain=audioContext.createGain();shamisenGain=audioContext.createGain();vocalGain=audioContext.createGain();shamisenGain.connect(masterGain);vocalGain.connect(masterGain);masterGain.connect(audioContext.destination)}updateMix(true)}
function updateMix(immediate=false){if(!audioContext||!masterGain||!shamisenGain||!vocalGain)return;const now=audioContext.currentTime,constant=immediate?.001:.02;masterGain.gain.setTargetAtTime(muted?0:.92,now,constant);shamisenGain.gain.setTargetAtTime((100-balance)/100,now,constant);vocalGain.gain.setTargetAtTime(balance/100,now,constant)}
function scheduleShamisen(frequency,when,noteCount){if(!audioContext||!shamisenGain||!Number.isFinite(frequency))return;const delay=Math.max(0,when-audioContext.currentTime),volume=noteCount>1?.62:.88;window.ShianAudioEngine.playFrequency(frequency,{exclusive:false,delay,volume,destination:shamisenGain}).catch(error=>{console.error(error);setStatus("三味線音源を再生できませんでした。",true)})}
function scheduleFlute(frequency,when,durationSeconds){if(!audioContext||!vocalGain||!Number.isFinite(frequency))return;const end=when+Math.max(.1,durationSeconds*.94),attack=Math.min(.045,durationSeconds*.2),release=Math.min(.09,durationSeconds*.28),gain=audioContext.createGain();gain.gain.setValueAtTime(.0001,when);gain.gain.linearRampToValueAtTime(.5,when+attack);gain.gain.setValueAtTime(.5,Math.max(when+attack,end-release));gain.gain.linearRampToValueAtTime(.0001,end);[{ratio:1,level:1},{ratio:2,level:.055}].forEach(partial=>{const oscillator=audioContext.createOscillator(),partialGain=audioContext.createGain();oscillator.type="sine";oscillator.frequency.setValueAtTime(frequency*partial.ratio,when);partialGain.gain.value=partial.level;oscillator.connect(partialGain).connect(gain);oscillator.start(when);oscillator.stop(end+.03);scheduled.push(oscillator)});gain.connect(vocalGain);scheduled.push({stop(){try{gain.disconnect()}catch(_){}}})}
function scheduleLegato(notes,secondsPerUnit){if(!audioContext||!vocalGain||notes.length<2)return;const frequencies=notes.map(frequencyFor);if(frequencies.some(value=>!Number.isFinite(value)))return;const start=startContextTime+notes[0].unit*secondsPerUnit,last=notes[notes.length-1],end=startContextTime+(last.unit+last.d)*secondsPerUnit,attack=Math.min(.045,(end-start)*.12),release=Math.min(.09,(end-start)*.18),gain=audioContext.createGain();gain.gain.setValueAtTime(.0001,start);gain.gain.linearRampToValueAtTime(.5,start+attack);gain.gain.setValueAtTime(.5,Math.max(start+attack,end-release));gain.gain.linearRampToValueAtTime(.0001,end);[{ratio:1,level:1},{ratio:2,level:.055}].forEach(partial=>{const oscillator=audioContext.createOscillator(),partialGain=audioContext.createGain();oscillator.type="sine";oscillator.frequency.setValueAtTime(frequencies[0]*partial.ratio,start);notes.slice(1).forEach((note,index)=>{const changeAt=startContextTime+note.unit*secondsPerUnit,glide=Math.min(.05,secondsPerUnit*.3),previous=frequencies[index]*partial.ratio,next=frequencies[index+1]*partial.ratio;oscillator.frequency.setValueAtTime(previous,Math.max(start,changeAt-glide/2));oscillator.frequency.linearRampToValueAtTime(next,changeAt+glide/2)});partialGain.gain.value=partial.level;oscillator.connect(partialGain).connect(gain);oscillator.start(start);oscillator.stop(end+.03);scheduled.push(oscillator)});gain.connect(vocalGain);scheduled.push({stop(){try{gain.disconnect()}catch(_){}}})}
async function play(){const playable=score&&[...score.notes,...score.vocalNotes].some(note=>!note.rest);if(!playable){setStatus("演奏できる音がありません。",true);return}try{await ensureAudio()}catch(error){setStatus(error instanceof Error?error.message:"音声を開始できません。",true);return}stopScheduled();const timeMap=buildTimeMap(),events=buildEvents(timeMap).filter(event=>event.unit>=pausedUnit);if(!events.length){pausedUnit=0;return play()}const secondsPerUnit=60/tempo/4,lead=.08;startContextTime=audioContext.currentTime+lead-pausedUnit*secondsPerUnit;playing=true;updateTransport();events.filter(event=>event.voice==="shamisen").forEach(event=>{const when=startContextTime+event.unit*secondsPerUnit,duration=event.duration*secondsPerUnit,notes=event.notes.filter(note=>!note.rest);notes.forEach(note=>{const frequency=frequencyFor(note);if(frequency)scheduleShamisen(frequency,when,notes.length)})});const vocalPlan=buildVocalPlan(timeMap);vocalPlan.phrases.forEach(phrase=>{const remaining=phrase.filter(note=>note.unit>=pausedUnit);if(remaining.length>1)scheduleLegato(remaining,secondsPerUnit);else if(remaining.length===1){const note=remaining[0],frequency=frequencyFor(note);if(frequency)scheduleFlute(frequency,startContextTime+note.unit*secondsPerUnit,note.d*secondsPerUnit)}});vocalPlan.singles.filter(note=>note.unit>=pausedUnit).forEach(note=>{const frequency=frequencyFor(note);if(frequency)scheduleFlute(frequency,startContextTime+note.unit*secondsPerUnit,note.d*secondsPerUnit)});const last=events[events.length-1],endUnit=Math.max(last.unit+last.duration,timeMap(Number(score.playbackEndUnit)||0));finishTimer=window.setTimeout(()=>{playing=false;pausedUnit=0;stopScheduled();updateTransport();setStatus("演奏が終わりました。")},Math.max(0,(startContextTime+endUnit*secondsPerUnit-audioContext.currentTime)*1000+100));setStatus(`${score.tuning}・${count}本・${tempo} BPM`)}
function stopScheduled(){window.ShianAudioEngine?.stopAll(.012);scheduled.forEach(node=>{try{node.stop()}catch(_){}});scheduled=[];if(finishTimer)window.clearTimeout(finishTimer);finishTimer=0}
function pause(){if(!playing||!audioContext)return;const secondsPerUnit=60/tempo/4;pausedUnit=Math.max(0,(audioContext.currentTime-startContextTime)/secondsPerUnit);playing=false;stopScheduled();updateTransport();setStatus("一時停止中")}
function stop(reset=false){if(playing&&audioContext&&!reset){const secondsPerUnit=60/tempo/4;pausedUnit=Math.max(0,(audioContext.currentTime-startContextTime)/secondsPerUnit)}playing=false;stopScheduled();if(reset)pausedUnit=0;updateTransport()}
function updateTransport(){$("#playPause").textContent=playing?"Ⅱ":"▶";$("#playPause").setAttribute("aria-label",playing?"一時停止":"再生");$("#mute").classList.toggle("muted",muted);$("#mute").textContent=muted?"♩":"♪"}
function setTempo(next){const resume=playing;if(resume)pause();tempo=clamp(Math.round(next),40,180);$("#tempo").value=String(tempo);$("#tempoValue").textContent=`${tempo} BPM`;if(resume)play()}
function setBalance(next){balance=clamp(Math.round(next),0,100);$("#balance").value=String(balance);$("#balanceValue").textContent=`三味線 ${100-balance}％・唄 ${balance}％`;updateMix()}
function renderCounts(){const labels=["一","二","三","四","五","六","七","八"];$(".counts").innerHTML=labels.map((label,index)=>`<button type="button" data-count="${index+1}" class="${index+1===count?"on":""}" aria-pressed="${index+1===count}">${label}</button>`).join("")}
window.addEventListener("message",event=>{if(event.origin!==location.origin)return;const validSource=event.source===window.opener||event.source===window.parent;if(!validSource)return;if(event.data?.type==="SHIAN_SCORE_UPDATE")receivePayload(event.data.payload);else if(event.data?.type==="SHIAN_PLAYER_STOP")stop(true)});
$(".counts").addEventListener("click",event=>{const button=event.target.closest("[data-count]");if(!button)return;count=Number(button.dataset.count);stop(true);renderCounts();if(score)setStatus(`${score.tuning}・${count}本`)});
$("#tempo").addEventListener("input",event=>setTempo(Number(event.target.value)));$("#tempoDown").addEventListener("click",()=>setTempo(tempo-5));$("#tempoUp").addEventListener("click",()=>setTempo(tempo+5));$("#balance").addEventListener("input",event=>setBalance(Number(event.target.value)));
$("#rewind").addEventListener("click",()=>{stop(true);setStatus(score?"先頭へ戻りました。":"演奏データを待っています。")});$("#playPause").addEventListener("click",()=>playing?pause():play());$("#mute").addEventListener("click",()=>{muted=!muted;updateMix();updateTransport()});
window.addEventListener("pagehide",()=>stop(true));document.addEventListener("visibilitychange",()=>{if(document.hidden&&playing)pause()});
renderCounts();setTempo(tempo);setBalance(balance);updateTransport();loadInitial();
})();
